[metadata]
description-file = README.md
license_files = LICENSE

[aliases]
test = pytest

[options.packages.find]
where = .
include = opendiscourse*
exclude = 
    tests
    examples
    docs
    scripts

[options.package_data]
* = *.yaml, *.yml, *.json, *.csv

[flake8]
max-line-length = 88
extend-ignore = E203
