apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-config
  namespace: kube-system
data:
  kubernetes.conf: |
    # Kubernetes configuration
    apiVersion: kubeadm.k8s.io/v1beta3
    kind: ClusterConfiguration
    kubernetesVersion: stable
    controlPlaneEndpoint: "172.28.158.179:6443"
    network:
      podSubnet: "10.244.0.0/16"
      serviceSubnet: "10.96.0.0/12"
    apiServer:
      extraArgs:
        authorization-mode: Node,RBAC
    controllerManager:
      extraArgs:
        horizontal-pod-autoscaler-use-rest-clients: "true"
        horizontal-pod-autoscaler-sync-period: "10s"
    etcd:
      local:
        dataDir: /var/lib/etcd
    certificatesDir: /etc/kubernetes/pki
    imageRepository: k8s.gcr.io
    ---
    apiVersion: kubeproxy.config.k8s.io/v1alpha1
    kind: KubeProxyConfiguration
    mode: ipvs
    ipvs:
      scheduler: rr
    ---
    apiVersion: kubelet.config.k8s.io/v1beta1
    kind: KubeletConfiguration
    cgroupDriver: systemd
    cpuManagerPolicy: static
    cpuManagerReconcilePeriod: 10s
    ---
    apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      name: default-deny-all
      namespace: default
    spec:
      podSelector: {}
      policyTypes:
      - Ingress
      - Egress
